import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.sass'
import ColorText from '@/components/Input/Input'

export default function Home() {
  return (
    <>
      <Head>
        <title>NameThatHex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <ColorText />
      </main>
    </>
  )
}
